Repository netlify/zip-it-and-ship-it, pull requests merged in 2020-04, with the labels that each got.

#89 Fix Go Functions
  README.md
  src/bin.js
  src/main.js
  src/main.test.js
Labels: type: bug

#91 Fix `skipGo` and `zipGo` options
  README.md
  src/bin.js
  src/main.js
  src/main.test.js
Labels: type: feature

#92 Upgrade dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  src/main.test.js
Labels: dependencies, type: chore

#90 Upgrade some dependencies related to npm audit problem
  package-lock.json
Labels: dependencies, type: security

#93 Fix `.eslintrc.json`
  .eslintrc.json
  src/bin.test.js
  src/dependencies.js
  src/helpers/main.js
  src/main.js
  src/main.test.js
  src/node.js
Labels: type: chore

#94 Remove pkg
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: type: chore

#95 Reorganize development setup
  .github/workflows/workflow.yml
  ava.config.js
  package-lock.json
  package.json
  scripts/coverage.sh
Labels: type: chore

#96 Test Ubuntu in CI
  .github/workflows/workflow.yml
Labels: type: chore

#97 Fix Windows support
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  src/main.test.js
  src/node.js
Labels: type: chore

#98 Fix some tests
  src/fixtures/ignore-dir-node-modules/node_modules/.gitkeep
  src/fixtures/node-module-typescript-types/function.js
  src/main.test.js
Labels: type: chore

#99 Do not bundle TypeScript types
  src/dependencies.js
  src/main.test.js
Labels: type: feature

#100 fix(dependencies): ignore `@prisma/cli`
  src/dependencies.js
Labels: type: feature
