Repository netlify/zip-it-and-ship-it, pull requests merged in 2020-12, with the labels that each got.

#255 Use native promisify instead of util.promisify
  package-lock.json
  package.json
  src/archive.js
  src/binary.js
  src/dependencies.js
  src/helpers/main.js
  src/main.js
  src/main.test.js
  src/node.js
Labels: type: chore

#256 Add metadata file to binary zip files.
  src/binary.js
  src/main.js
  src/main.test.js
Labels: type: bug

#262 Add `.vscode` to `.gitignore`
  .gitignore
Labels: type: chore

#263 Use `Set` in Node.js dependencies logic
  src/dependencies.js
Labels: type: chore

#265 chore: add commit linting
  commitlint.config.js
  package-lock.json
  package.json
Labels: type: chore

#264 Rename variables
  src/dependencies.js
Labels: type: chore

#242 feat(js): add list of tree shakable external dependencies
  src/dependencies.js
  src/fixtures/node-module-next-on-netlify/function/function.js
  src/fixtures/node-module-next-on-netlify/function/renderNextPage.js
  src/fixtures/node-module-next-on-netlify/node_modules/next/dist/compiled/semver.js
  src/fixtures/node-module-next-on-netlify/node_modules/next/dist/next-server/lib/constants.js
  src/fixtures/node-module-next-on-netlify/node_modules/next/dist/other.js
  src/fixtures/node-module-next-on-netlify/node_modules/next/index.js
  src/fixtures/node-module-next-on-netlify/node_modules/next/package.json
  src/fixtures/node-module-next/function.js
  src/fixtures/node-module-next/node_modules/next/dist/compiled/semver.js
  src/fixtures/node-module-next/node_modules/next/dist/next-server/lib/constants.js
  src/fixtures/node-module-next/node_modules/next/dist/other.js
  src/fixtures/node-module-next/node_modules/next/index.js
  src/fixtures/node-module-next/node_modules/next/package.json
  src/main.test.js
Labels: type: feature

#266 chore: add release PR flow
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: type: chore

#267 refactor: add missing parenthesis to comment
  src/dependencies.js
Labels: type: chore

#268 Use `@netlify/eslint-config-node`
  .eslintrc.js
  .eslintrc.json
  .gitattributes
  .github/ISSUE_TEMPLATE.md
  .github/workflows/workflow.yml
  .gitignore
  .prettierrc.json
  README.md
  ava.config.js
  package-lock.json
  package.json
  scripts/coverage.sh
  src/archive.js
  src/bin.js
  src/bin.test.js
  src/binary.js
  src/dependencies.js
  src/fixtures/invalid-require/function.js
  src/fixtures/local-parent-require/function/function.js
  src/fixtures/many-dependencies/function.js
  src/fixtures/no-package-json/function.js
  src/fixtures/node-module-deep-conditional/function.js
  src/fixtures/node-module-error/function.js
  src/fixtures/node-module-excluded/function.js
  src/fixtures/node-module-missing-conditional/function.js
  src/fixtures/node-module-missing-deep/function.js
  src/fixtures/node-module-missing-optional/function.js
  src/fixtures/node-module-missing-package/function.js
  src/fixtures/node-module-missing/function.js
  src/fixtures/node-module-next-on-netlify/function/function.js
  src/fixtures/node-module-next-on-netlify/function/renderNextPage.js
  src/fixtures/node-module-next/function.js
  src/fixtures/node-module-peer-not-optional/function.js
  src/fixtures/node-module-peer-optional-none/function.js
  src/fixtures/node-module-peer-optional/function.js
  src/fixtures/node-module-scope/function.js
  src/fixtures/node-module-typescript-types/function.js
  src/fixtures/symlinks/function/function.js
  src/helpers/main.js
  src/helpers/sha.js
  src/main.js
  src/main.test.js
  src/node.js
  src/resolve.js
Labels: type: chore

#272 Enable `no-shadow` ESLint rule
  .eslintrc.js
  src/node.js
  src/resolve.js
Labels: type: chore

#271 Rename a file
  src/main.js
  src/runtime.js
Labels: type: chore

#273 Enable `require-await` ESLint rule
  .eslintrc.js
  src/resolve.js
Labels: type: chore

#270 Enable `max-params` rule
  .eslintrc.js
  src/main.js
  src/runtime.js
  tests/helpers/main.js
  tests/main.js
Labels: type: chore

#274 Add `node/prefer-global/buffer` ESLint rule
  .eslintrc.js
  src/node.js
Labels: type: chore

#275 Enable `promise/param-names` ESLint rule
  .eslintrc.js
  src/resolve.js
Labels: type: chore

#276 Enable `fp/no-mutating-methods` ESLint rule
  .eslintrc.js
  src/dependencies.js
Labels: type: chore

#280 Enable the `complexity` ESLint rule
  .eslintrc.js
  src/main.js
Labels: type: chore

#279 Enable `max-depth` ESLint rule
  .eslintrc.js
  src/resolve.js
Labels: type: chore

#278 Enable `no-magic-numbers` ESLint rule
  .eslintrc.js
  src/archive.js
  src/main.js
  tests/main.js
Labels: type: chore

#277 Enable some ESLint rules against dynamic `require()`
  .eslintrc.js
  src/dependencies.js
  tests/fixtures/invalid-require/function.js
  tests/fixtures/many-dependencies/function.js
  tests/fixtures/node-module-excluded/function.js
  tests/fixtures/node-module-missing-conditional/function.js
  tests/fixtures/node-module-missing-optional/function.js
  tests/fixtures/node-module-peer-not-optional/function.js
  tests/fixtures/node-module-peer-optional-none/function.js
  tests/fixtures/node-module-peer-optional/function.js
  tests/fixtures/node-module-typescript-types/function.js
  tests/fixtures/side-module/function.js
  tests/main.js
Labels: type: chore

#281 Break down into smaller files
  .eslintrc.js
  src/info.js
  src/main.js
  src/node_dependencies/index.js
  src/node_dependencies/nested.js
  src/node_dependencies/package_json.js
  src/node_dependencies/published.js
  src/node_dependencies/resolve.js
  src/zip_node.js
Labels: type: chore
