Repository netlify/zip-it-and-ship-it, pull requests merged in 2020-11, with the labels that each got.

#234 Add `--fail` flag to `curl` for Codecov
  scripts/coverage.sh
Labels: type: chore

#235 github tools: fix fossa workflow file
  .github/workflows/fossa.yml
Labels: type: chore

#236 Fix tests on Windows
  src/bin.test.js
Labels: type: bug

#241 fix: fossa
  .github/workflows/fossa.yml
Labels: type: bug

#243 Improve error message
  src/dependencies.js
Labels: type: chore

#226 feat(binary): improve binary file detection
  README.md
  package-lock.json
  package.json
  src/binary.js
  src/fixtures/rust-simple/hello-world
  src/go.js
  src/main.js
  src/main.test.js
Labels: type: feature
