Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-04, with the labels that each got.

#404 feat: add errorInfo property to esbuild bundling errors
  src/runtimes/node/bundler.js
  src/runtimes/node/index.js
  src/runtimes/node/zip_esbuild.js
  src/zip.js
  tests/main.js
Labels: type: feature

#406 chore: automate npm publishing
  .github/workflows/release-please.yml
  CONTRIBUTING.md
Labels: type: chore

#408 chore: rename default branch from master to main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/fossa.yml
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
  README.md
  codecov.yml
  renovate.json5
Labels: type: chore

#411 chore: add benchmark
  .github/workflows/benchmark.yml
  .gitignore
  benchmarks/fixtures/function_1.js
  benchmarks/fixtures/function_2.js
  benchmarks/fixtures/package-lock.json
  benchmarks/fixtures/package.json
  benchmarks/helpers/main.js
  benchmarks/index.js
  benchmarks/run.sh
  package-lock.json
  package.json
Labels: type: chore

#410 feat: add archiveFormat configuration property
  README.md
  package-lock.json
  package.json
  src/bin.js
  src/runtimes/node/index.js
  src/runtimes/node/zip_esbuild.js
  src/runtimes/node/zip_zisi.js
  src/utils/consts.js
  src/zip.js
  src/zip_node.js
  tests/helpers/main.js
  tests/main.js
Labels: type: feature

#412 chore(release-please): use GitHub app token
  .github/workflows/release-please.yml
Labels: type: chore

#419 chore: add Next.js site to benchmark
  benchmarks/fixtures/function_2.js
  benchmarks/fixtures/next_api_hello/createRequestObject.js
  benchmarks/fixtures/next_api_hello/createResponseObject.js
  benchmarks/fixtures/next_api_hello/nextPage.js
  benchmarks/fixtures/next_api_hello/next_api_hello.js
  benchmarks/fixtures/next_api_hello/renderNextPage.js
  benchmarks/fixtures/next_image.js
  benchmarks/fixtures/next_index/createRequestObject.js
  benchmarks/fixtures/next_index/createResponseObject.js
  benchmarks/fixtures/next_index/nextPage.js
  benchmarks/fixtures/next_index/next_index.js
  benchmarks/fixtures/next_index/renderNextPage.js
  benchmarks/fixtures/next_index_2/createRequestObject.js
  benchmarks/fixtures/next_index_2/createResponseObject.js
  benchmarks/fixtures/next_index_2/nextPage.js
  benchmarks/fixtures/next_index_2/next_index_2.js
  benchmarks/fixtures/next_index_2/renderNextPage.js
  benchmarks/fixtures/next_index_3/createRequestObject.js
  benchmarks/fixtures/next_index_3/createResponseObject.js
  benchmarks/fixtures/next_index_3/nextPage.js
  benchmarks/fixtures/next_index_3/next_index_3.js
  benchmarks/fixtures/next_index_3/renderNextPage.js
  benchmarks/fixtures/next_index_4/createRequestObject.js
  benchmarks/fixtures/next_index_4/createResponseObject.js
  benchmarks/fixtures/next_index_4/nextPage.js
  benchmarks/fixtures/next_index_4/next_index_4.js
  benchmarks/fixtures/next_index_4/renderNextPage.js
  benchmarks/fixtures/package-lock.json
  benchmarks/fixtures/package.json
  benchmarks/helpers/main.js
  benchmarks/index.js
Labels: type: chore

#421 chore: add sample test to benchmark
  benchmarks/helpers/sample.js
  benchmarks/index.js
Labels: type: chore

#418 feat: add plugin to detect native modules
  package-lock.json
  package.json
  src/runtimes/node/bundler.js
  src/runtimes/node/native_modules/detector.js
  src/runtimes/node/native_modules/plugin.js
  src/runtimes/node/zip_esbuild.js
  tests/fixtures/node-module-native-buildtime/function.js
  tests/fixtures/node-module-native-buildtime/node_modules/test/index.js
  tests/fixtures/node-module-native-buildtime/node_modules/test/native.node
  tests/fixtures/node-module-native-buildtime/node_modules/test/package.json
  tests/fixtures/node-module-native-buildtime/node_modules/test/side-file.js
  tests/fixtures/node-module-native-buildtime/package.json
  tests/fixtures/node-module-native-runtime/function.js
  tests/fixtures/node-module-native-runtime/node_modules/nan/index.js
  tests/fixtures/node-module-native-runtime/node_modules/nan/package.json
  tests/fixtures/node-module-native-runtime/node_modules/test/index.js
  tests/fixtures/node-module-native-runtime/node_modules/test/native.node
  tests/fixtures/node-module-native-runtime/node_modules/test/package.json
  tests/fixtures/node-module-native-runtime/node_modules/test/side-file.js
  tests/fixtures/node-module-native-runtime/package.json
  tests/main.js
Labels: type: feature

#423 feat: add function name to output of zipFunction and zipFunctions
  src/zip.js
  tests/main.js
Labels: type: feature

#427 chore: update benchmarks
  .github/workflows/benchmark.yml
  benchmarks/esbuild.js
  benchmarks/helpers/sample.js
  benchmarks/run.sh
  benchmarks/zisi.js
Labels: type: chore

#425 feat: add nodeVersion config property
  README.md
  src/runtimes/node/bundler.js
  src/runtimes/node/bundler_target.js
  src/runtimes/node/zip_esbuild.js
  tests/fixtures/node-module-optional-catch-binding/function.js
  tests/main.js
Labels: type: feature

#426 feat: add config property to CLI entry point
  src/bin.js
  tests/main.js
Labels: type: feature

#432 chore: add logo to README
  README.md
  zip-it-and-ship-it.png
Labels: type: chore

#433 feat: add `nativeNodeModules` property to output
  src/runtimes/node/bundler.js
  src/runtimes/node/native_modules/plugin.js
  src/runtimes/node/zip_esbuild.js
  src/zip.js
  tests/fixtures/node-module-native-buildtime/package.json
  tests/main.js
Labels: type: feature

#435 fix: add .ts to the list of esbuild resolved extensions
  src/runtimes/node/bundler.js
  tests/fixtures/node-typescript-with-imports/function.ts
  tests/fixtures/node-typescript-with-imports/lib/util.ts
  tests/main.js
Labels: type: bug

#436 feat: add `mainFile` to output of `zipFunction`/`zipFunctions`
  src/zip.js
  tests/main.js
Labels: type: feature

#437 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: chore

#439 feat: add inputs property
  src/runtimes/node/bundler.js
  src/runtimes/node/zip_esbuild.js
  src/runtimes/node/zip_zisi.js
  src/zip.js
  tests/fixtures/node-module-and-local-imports/function.js
  tests/fixtures/node-module-and-local-imports/lib/file1.js
  tests/fixtures/node-module-and-local-imports/lib2/file2.js
  tests/fixtures/node-module-and-local-imports/lib2/unused_file.js
  tests/fixtures/node-module-and-local-imports/node_modules/test-child/index.js
  tests/fixtures/node-module-and-local-imports/node_modules/test-child/package.json
  tests/fixtures/node-module-and-local-imports/node_modules/test-child/unused_file.js
  tests/fixtures/node-module-and-local-imports/node_modules/test/index.js
  tests/fixtures/node-module-and-local-imports/node_modules/test/package.json
  tests/fixtures/node-module-and-local-imports/node_modules/test/unused_file.js
  tests/fixtures/node-module-and-local-imports/package.json
  tests/main.js
Labels: type: feature

#441 feat: add support for included_files config property
  src/runtimes/node/src_files.js
  src/runtimes/node/zip_esbuild.js
  src/runtimes/node/zip_zisi.js
  tests/fixtures/included_files/content/post1.md
  tests/fixtures/included_files/content/post2.md
  tests/fixtures/included_files/content/post3.md
  tests/fixtures/included_files/netlify/functions/func1.js
  tests/fixtures/included_files/node_modules/test/index.js
  tests/fixtures/included_files/node_modules/test/package.json
  tests/fixtures/included_files/node_modules/test/test.html
  tests/fixtures/included_files/node_modules/test/test.map
  tests/fixtures/included_files/package.json
  tests/helpers/main.js
  tests/main.js
Labels: type: feature
