Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-05, with the labels that each got.

#447 feat: add support for sourcemaps
  src/runtimes/node/bundler.js
  src/runtimes/node/zip_esbuild.js
  src/utils/fs.js
  src/zip_node.js
  tests/main.js
Labels: type: feature

#454 fix: use URLs in sourceRoot
  src/runtimes/node/bundler.js
Labels: type: bug

#458 feat: add `nodeModulesWithDynamicImports` property
  package-lock.json
  package.json
  src/runtimes/node/bundler.js
  src/runtimes/node/dynamic_imports.js
  src/runtimes/node/zip_esbuild.js
  src/zip.js
  tests/fixtures/node-module-dynamic-import-invalid/function.js
  tests/fixtures/node-module-dynamic-import-invalid/node_modules/@org/test/files/one.json
  tests/fixtures/node-module-dynamic-import-invalid/node_modules/@org/test/index.js
  tests/fixtures/node-module-dynamic-import-invalid/node_modules/test-two/files/one.json
  tests/fixtures/node-module-dynamic-import-invalid/node_modules/test-two/index.js
  tests/fixtures/node-module-dynamic-import-invalid/package.json
  tests/fixtures/node-module-dynamic-import/function.js
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test/files/one.json
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test/index.js
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test/package.json
  tests/fixtures/node-module-dynamic-import/node_modules/test-two/files/one.json
  tests/fixtures/node-module-dynamic-import/node_modules/test-two/index.js
  tests/fixtures/node-module-dynamic-import/node_modules/test-two/package.json
  tests/fixtures/node-module-dynamic-import/package.json
  tests/main.js
Labels: type: feature

#464 fix: upgrade archiver to 5.x
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  src/archive.js
Labels: type: bug

#466 ci: use Node.js 16 in release please and benchmark
  .github/workflows/benchmark.yml
  .github/workflows/release-please.yml
Labels: type: bug, type: chore

#471 chore: update README
  README.md
Labels: init/es-func-bundle, type: chore

#472 chore: run CI on `latest` Node.js
  .github/workflows/benchmark.yml
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore

#475 chore: fix test coverage upload
  .github/workflows/workflow.yml
Labels: type: chore

#478 feat: remove Node 8 support
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  renovate.json5
  src/archive.js
  tests/fixtures/node-module-optional-catch-binding/function.js
Labels: init/deprecate-node-8, type: feature

#474 feat: remove src directory from function bundle
  src/runtimes/node/index.js
  src/runtimes/node/src_files.js
  src/runtimes/node/zip_esbuild.js
  src/runtimes/node/zip_zisi.js
  src/zip.js
  src/zip_node.js
  tests/fixtures/base_path/content/post1.md
  tests/fixtures/base_path/content/post2.md
  tests/fixtures/base_path/content/post3.md
  tests/fixtures/base_path/func2.js
  tests/fixtures/base_path/netlify/functions1/func1.js
  tests/fixtures/base_path/netlify/functions2/func2.js
  tests/fixtures/base_path/node_modules/test/index.js
  tests/fixtures/base_path/node_modules/test/package.json
  tests/fixtures/base_path/node_modules/test/test.html
  tests/fixtures/base_path/node_modules/test/test.map
  tests/fixtures/base_path/package.json
  tests/main.js
Labels: type: feature

#501 chore: add packageRules to Renovate config
  renovate.json5
Labels: type: chore

#504 chore(renovate): remove redundant rule
  renovate.json5
Labels: type: chore
