Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-10, with the labels that each got.

#695 chore: refactor `testMany` test util
  tests/helpers/test_bundlers.js
  tests/helpers/test_many.js
  tests/main.js
Labels: type: chore

#697 chore: keep pkg-dir at v5 (closes #694)
  renovate.json5
Labels: type: chore, automerge

#699 chore: add test variation for `parseWithEsbuild` feature flag
  package-lock.json
  package.json
  tests/helpers/test_many.js
  tests/main.js
Labels: type: chore, automerge

#701 chore: add autocomplete to testMany variations arg
  tests/helpers/test_many.js
Labels: type: chore, automerge

#703 chore: remove ESLint directives from tests file
  .eslintrc.js
  tests/main.js
Labels: type: chore

#675 chore: add TypeScript build step
  .gitignore
  benchmarks/run.sh
  package-lock.json
  package.json
  src/node_dependencies/tree_files.ts
  tests/bin.js
  tests/helpers/main.js
  tests/main.js
  tsconfig.json
Labels: type: chore, type: feature

#673 fix: allow Node modules to be excluded from the bundle
  package.json
  src/node_dependencies/traverse.js
  src/runtimes/node/src_files.js
  tests/main.js
Labels: type: feature, type: bug

#706 chore: run build step in Next e2e workflow
  .github/workflows/e2e-nextjs.yml
Labels: type: chore
