Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-11, with the labels that each got.

#786 fix: disable ESM transpilation in NFT
  src/runtimes/node/bundlers/nft/index.ts
  tests/main.js
Labels: type: bug

#788 refactor: restructure usage of `pluginsModulesPath` property
  src/main.ts
  src/runtimes/node/bundlers/esbuild/src_files.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/bundlers/zisi/src_files.ts
  src/runtimes/node/index.ts
  src/runtimes/node/utils/plugin_modules_path.ts
  src/runtimes/node/utils/zip.ts
  src/runtimes/runtime.ts
  src/zip.ts
Labels: type: chore

#789 chore: add test
  tests/main.js
Labels: type: chore

#790 feat: reinstate ESM transpilation for NFT
  src/feature_flags.ts
  src/runtimes/node/bundlers/nft/es_modules.ts
  src/runtimes/node/bundlers/nft/index.ts
  src/runtimes/node/bundlers/nft/transpile.ts
  tests/fixtures/local-require-esm/function_cjs/function_cjs.js
  tests/helpers/main.js
  tests/main.js
Labels: type: feature

#698 chore: add test for `node:` prefix
  tests/fixtures/node-force-builtin/function.js
  tests/main.js
Labels: type: bug

#798 Make sure that consumers use Precinct 8.2
  package.json
Labels: type: bug

#800 fix: sanitise package.json files field
  src/runtimes/node/utils/package_json.ts
  tests/unit.js
Labels: type: bug

#802 fix: esm imports with node: prefix on esbuild
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/plugin_node_builtin.ts
  tests/fixtures/node-force-builtin-esm/function.js
  tests/main.js
Labels: type: bug, automerge

#806 fix: compile away `node:`-namespaced imports
  src/runtimes/node/bundlers/esbuild/plugin_node_builtin.ts
  tests/fixtures/node-force-builtin-cjs/function.js
  tests/fixtures/node-force-builtin-v16/function.js
  tests/main.js
Labels: type: bug

#813 chore: remove unneeded v16 test
  tests/fixtures/node-force-builtin-v16/function.js
  tests/main.js
Labels: type: chore, automerge

#807 fix: only transpile ESM imports when entrypoint is ESM
  src/runtimes/node/bundlers/nft/es_modules.ts
  tests/fixtures/node-cjs-importing-mjs/function.js
  tests/fixtures/node-cjs-importing-mjs/lib/file.mjs
  tests/main.js
Labels: type: bug

#816 fix: ensure directories are created before writing files
  src/runtimes/node/utils/zip.ts
  src/utils/fs.ts
  tests/main.js
Labels: type: bug

#817 chore: update E2E workflow
  .github/workflows/integration-tests.yml
Labels: type: chore, automerge

#818 feat: add sourcemap support to NFT
  package-lock.json
  package.json
  src/runtimes/node/bundlers/nft/transpile.ts
  tests/fixtures/esm-throwing-error/.eslintrc
  tests/fixtures/esm-throwing-error/function.js
  tests/main.js
Labels: type: feature, automerge

#819 feat: add new top-level `schedule` property
  src/manifest.ts
  src/utils/format_result.ts
  tests/fixtures/with-schedule/func-1.js
  tests/main.js
Labels: type: feature

#835 chore: simplify `renovate.json5`
  renovate.json5
Labels: type: chore

#836 chore!: drop support for Node 10
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  src/main.ts
  src/runtimes/node/bundlers/zisi/traverse.ts
  src/utils/polyfills.ts
Labels: type: chore

#834 feat: add in-source config declaration support
  src/feature_flags.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/index.ts
  src/runtimes/node/bundlers/esbuild/plugin_in_source_config.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/in_source_config/index.ts
  src/runtimes/node/in_source_config/properties/schedule.ts
  src/runtimes/node/index.ts
  src/runtimes/node/parser/exports.ts
  src/runtimes/node/parser/helpers.ts
  src/runtimes/node/parser/imports.ts
  src/runtimes/node/parser/index.ts
  src/runtimes/runtime.ts
  src/utils/format_result.ts
  tests/fixtures/in-source-config/functions/cron_cjs.js
  tests/fixtures/in-source-config/functions/cron_cjs_renamed.js
  tests/fixtures/in-source-config/functions/cron_esm.js
  tests/fixtures/in-source-config/functions/cron_esm_renamed.js
  tests/fixtures/in-source-config/functions/cron_ts.ts
  tests/fixtures/in-source-config/functions/cron_ts_renamed.ts
  tests/fixtures/in-source-config/node_modules/@netlify/functions/index.js
  tests/fixtures/in-source-config/node_modules/@netlify/functions/package.json
  tests/fixtures/in-source-config/package.json
  tests/main.js
Labels: type: feature

#841 chore: make Renovate ignore modules in fixtures
  renovate.json5
Labels: type: chore

#847 feat: extend in-source configuration to all Node bundlers
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/index.ts
  src/runtimes/node/bundlers/esbuild/plugin_in_source_config.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/in_source_config/index.ts
  src/runtimes/node/index.ts
  tests/main.js
Labels: type: feature
