Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-08, with the labels that each got.

#601 feat: add support for manifest file
  README.md
  src/bin.js
  src/manifest.js
  src/utils/fs.js
  src/zip.js
  tests/main.js
Labels: type: feature

#604 chore: add kodiak
  .github/.kodiak.toml
Labels: type: chore

#606 feat: add `rustTargetDirectory` config property
  README.md
  src/runtimes/rust/builder.js
  src/runtimes/rust/index.js
  tests/fixtures/rust-source/rust-func-2/.gitignore
  tests/fixtures/rust-source/rust-func-2/Cargo.lock
  tests/fixtures/rust-source/rust-func-2/Cargo.toml
  tests/fixtures/rust-source/rust-func-2/src/main.rs
  tests/main.js
Labels: type: feature, automerge

#614 feat: simplify manifest format
  src/manifest.js
  tests/main.js
Labels: type: feature

#616 feat: improve custom error tagging
  src/runtimes/go/builder.js
  src/runtimes/node/bundler.js
  src/runtimes/rust/builder.js
  tests/fixtures/go-source-multiple/go-func-1/main.go
  tests/fixtures/go-source-multiple/go-func-2/go-func-2.go
  tests/fixtures/go-source-multiple/go-func-2/go.mod
  tests/fixtures/go-source-multiple/go-func-2/go.sum
  tests/fixtures/rust-source-multiple/rust-func-1/.gitignore
  tests/fixtures/rust-source-multiple/rust-func-1/Cargo.lock
  tests/fixtures/rust-source-multiple/rust-func-1/Cargo.toml
  tests/fixtures/rust-source-multiple/rust-func-1/src/main.rs
  tests/fixtures/rust-source-multiple/rust-func-2/.gitignore
  tests/fixtures/rust-source-multiple/rust-func-2/Cargo.lock
  tests/fixtures/rust-source-multiple/rust-func-2/Cargo.toml
  tests/fixtures/rust-source-multiple/rust-func-2/src/main.rs
  tests/main.js
Labels: type: feature

#621 bug: patch fossa install process
  .github/workflows/fossa.yml
Labels: type: chore

#624 chore: update fossa branch
  .github/workflows/fossa.yml
Labels: type: chore, automerge

#619 feat: allow JS functions with `.mjs` extension
  src/runtimes/node/finder.js
  src/runtimes/node/index.js
  tests/fixtures/node-mjs/func1.mjs
  tests/fixtures/node-mjs/func2/func2.mjs
  tests/fixtures/node-mjs/func3/index.mjs
  tests/main.js
Labels: type: feature, automerge

#635 chore(ci): cache npm cache dir between workflow execs
  .github/workflows/benchmark.yml
  .github/workflows/e2e-nextjs.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore, automerge
