Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-09, with the labels that each got.

#645 chore: create CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore

#654 chore: pin version of adm-zip
  package.json
  renovate.json5
Labels: type: chore, automerge

#655 chore(ci): fix our npm caching strategy for our e2e nextjs tests
  .github/workflows/e2e-nextjs.yml
Labels: type: chore, automerge

#625 feat: use esbuild by default for es modules, if detected
  README.md
  package-lock.json
  package.json
  src/feature_flags.js
  src/runtimes/node/detect_es_module.js
  src/runtimes/node/index.js
  src/zip.js
  tests/fixtures/local-require-esm/.eslintrc
  tests/fixtures/local-require-esm/function_export_only/function_export_only.js
  tests/fixtures/local-require-esm/function_import_only/function_import_only.js
  tests/main.js
Labels: type: feature, automerge

#603 feat: change default value of `processDynamicNodeImports`
  src/runtimes/node/bundler.js
  tests/main.js
Labels: type: feature

#663 feat: replace acorn with @babel/parser
  package-lock.json
  package.json
  src/runtimes/node/dynamic_imports/parser.js
Labels: type: feature, automerge

#659 feat: replace precinct with esbuild
  package-lock.json
  package.json
  src/feature_flags.js
  src/main.js
  src/node_dependencies/index.js
  src/runtimes/node/index.js
  src/runtimes/node/list_imports.js
  src/runtimes/node/src_files.js
  src/runtimes/node/zip_zisi.js
  tests/fixtures/local-node-module-deep-require/function.js
  tests/fixtures/local-node-module-deep-require/node_modules/@netlify/mock-package/index.js
  tests/fixtures/local-node-module-deep-require/node_modules/@netlify/mock-package/package.json
  tests/fixtures/local-node-module-deep-require/node_modules/@netlify/mock-package/stack.js
  tests/fixtures/local-node-module-deep-require/package.json
  tests/helpers/main.js
  tests/main.js
Labels: type: feature, automerge

#674 fix: improve native module detection
  src/runtimes/node/native_modules/detector.js
  tests/fixtures/node-module-native-buildtime/function.js
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-file/index.js
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-file/native.node
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-file/package.json
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-file/side-file.js
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-gyp/index.js
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-gyp/native.node
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-gyp/package.json
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-node-gyp/side-file.js
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-prebuild/index.js
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-prebuild/native.node
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-prebuild/package.json
  tests/fixtures/node-module-native-buildtime/node_modules/module-with-prebuild/side-file.js
  tests/fixtures/node-module-native-buildtime/package.json
  tests/main.js
Labels: type: bug

#671 fix: limit `nodeModulesWithDynamicImports` to unresolved imports
  src/runtimes/node/dynamic_imports/plugin.js
  tests/fixtures/node-module-dynamic-import/function.js
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test_2/files/one.json
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test_2/index.js
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test_2/package.json
  tests/fixtures/node-module-dynamic-import/node_modules/test-three/index.js
  tests/fixtures/node-module-dynamic-import/node_modules/test-three/one.json
  tests/fixtures/node-module-dynamic-import/node_modules/test-three/package.json
  tests/fixtures/node-module-dynamic-import/package.json
  tests/main.js
Labels: type: bug, automerge

#681 fix: force esbuild target in zisi
  src/runtimes/node/list_imports.js
  tests/fixtures/local-node-module-destructure-require/function.js
  tests/fixtures/local-node-module-destructure-require/node_modules/@netlify/mock-package/index.js
  tests/fixtures/local-node-module-destructure-require/node_modules/@netlify/mock-package/package.json
  tests/fixtures/local-node-module-destructure-require/node_modules/@netlify/mock-package/stack.js
  tests/fixtures/local-node-module-destructure-require/package.json
  tests/fixtures/local-node-module-destructure-require/tsconfig.json
  tests/main.js
Labels: type: bug

#657 feat: pnpm-style symlinking (#636)
  tests/fixtures/node-module-symlinks/function.js
  tests/fixtures/node-module-symlinks/node_modules/is-even
  tests/fixtures/node-module-symlinks/package.json
  tests/fixtures/node_modules/.pnpm/is-even@1.0.0/node_modules/is-even/index.js
  tests/fixtures/node_modules/.pnpm/is-even@1.0.0/node_modules/is-even/package.json
  tests/fixtures/node_modules/.pnpm/is-even@1.0.0/node_modules/is-odd
  tests/fixtures/node_modules/.pnpm/is-odd@1.0.0/node_modules/is-odd/index.js
  tests/fixtures/node_modules/.pnpm/is-odd@1.0.0/node_modules/is-odd/package.json
  tests/main.js
Labels: type: feature, type: bug, automerge
