Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-03, with the labels that each got.

#350 fix: fix and test dynamic import()
  src/node_dependencies/index.js
  tests/fixtures/dynamic-import/.eslintrc
  tests/fixtures/dynamic-import/function.js
  tests/main.js
Labels: type: bug

#347 fix: treat @prisma/client as an external module
  src/node_dependencies/special_cases.js
  src/runtimes/node.js
  tests/main.js
Labels: type: bug

#353 fix: detect native bindings and change extension priority
  src/node_bundler/index.js
  src/node_bundler/plugins.js
  src/runtimes/node.js
  tests/fixtures/node-fetch/function.js
  tests/fixtures/node-fetch/node_modules/node-fetch/lib/index.js
  tests/fixtures/node-fetch/node_modules/node-fetch/lib/index.mjs
  tests/fixtures/node-fetch/node_modules/node-fetch/package.json
  tests/fixtures/node-fetch/package.json
  tests/main.js
Labels: type: bug

#355 fix: remove esbuild plugin
  src/node_bundler/index.js
  tests/main.js
Labels: type: bug

#357 feat: use esbuild log output
  src/node_bundler/index.js
Labels: type: feature

#360 chore: fix `semver` version with Node 8
  package-lock.json
  package.json
  renovate.json5
Labels: type: chore

#364 feat: add support for TypeScript
  src/info.js
  src/main.js
  src/node_bundler/index.js
  src/runtime.js
  src/runtimes/detect_runtime.js
  src/runtimes/go.js
  src/runtimes/index.js
  src/runtimes/node/finder.js
  src/runtimes/node/index.js
  src/runtimes/rust.js
  src/utils/consts.js
  src/utils/fs.js
  src/zip.js
  src/zip_binary.js
  src/zip_node.js
  tests/fixtures/conflicting-names-1/foo.txt
  tests/fixtures/conflicting-names-1/function.js
  tests/fixtures/conflicting-names-1/function/function.js
  tests/fixtures/conflicting-names-1/function/index.js
  tests/fixtures/conflicting-names-2/function.js
  tests/fixtures/conflicting-names-2/function/index.js
  tests/fixtures/conflicting-names-3/function/index.js
  tests/fixtures/conflicting-names-3/function/index.ts
  tests/fixtures/conflicting-names-4/function.js
  tests/fixtures/conflicting-names-4/function.ts
  tests/fixtures/node-typescript-directory-1/function/function.ts
  tests/fixtures/node-typescript-directory-2/function/index.ts
  tests/fixtures/node-typescript/function.ts
  tests/main.js
Labels: type: feature

#369 chore: remove unused plugins file
  src/node_bundler/plugins.js
Labels: type: chore

#370 feat: make esbuild the default bundler for TypeScript functions
  src/bin.js
  src/runtimes/node/bundler.js
  src/runtimes/node/index.js
  src/runtimes/node/src_files.js
  src/runtimes/node/zip_esbuild.js
  src/runtimes/node/zip_zisi.js
  tests/main.js
Labels: type: feature

#374 fix: make JS files take precedence over TS files with the same name
  src/runtimes/node/finder.js
  tests/fixtures/conflicting-names-5/function.js
  tests/fixtures/conflicting-names-5/function.zip
  tests/main.js
Labels: type: bug

#377 chore: run CI tests on latest Node 15.*
  .github/workflows/workflow.yml
Labels: type: chore

#373 chore!: remove `zipGo`/`skipGo` options
  README.md
  src/bin.js
  src/runtimes/go.js
  src/zip.js
  tests/main.js
Labels: type: chore

#376 feat!: add config property
  README.md
  package-lock.json
  package.json
  src/config.js
  src/main.js
  src/runtimes/index.js
  src/runtimes/node/index.js
  src/runtimes/node/src_files.js
  src/runtimes/node/zip_esbuild.js
  src/zip.js
  tests/fixtures/config-apply-1/another_function.js
  tests/fixtures/config-apply-1/function_one.js
  tests/fixtures/config-apply-1/function_two.js
  tests/fixtures/config-apply-1/node_modules/test-1/index.js
  tests/fixtures/config-apply-1/node_modules/test-1/package.json
  tests/fixtures/config-apply-1/node_modules/test-2/index.js
  tests/fixtures/config-apply-1/node_modules/test-2/package.json
  tests/fixtures/config-apply-1/node_modules/test-3/index.js
  tests/fixtures/config-apply-1/node_modules/test-3/package.json
  tests/fixtures/config-apply-1/package.json
  tests/main.js
Labels: init/es-func-bundle, proj/func-config-api, type: feature

#385 feat!: add nodeBundler config property
  README.md
  src/main.js
  src/runtimes/go.js
  src/runtimes/node/index.js
  src/runtimes/node/src_files.js
  src/runtimes/node/zip_esbuild.js
  src/runtimes/node/zip_zisi.js
  src/runtimes/rust.js
  src/zip.js
  tests/helpers/main.js
  tests/main.js
Labels: init/es-func-bundle, proj/func-config-api, type: feature

#388 fix: ignore undefined values when computing function config
  src/config.js
  tests/main.js
Labels: init/es-func-bundle, proj/func-config-api, type: bug
