Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-12, with the labels that each got.

#877 feat: detect exports.handler in ISC
  src/runtimes/node/parser/exports.ts
  tests/fixtures/in-source-config/functions/cron_cjs_exports.js
  tests/main.js
Labels: type: feature, automerge

#884 feat: remove `parseISC` feature flag
  src/feature_flags.ts
  src/runtimes/node/index.ts
  tests/main.js
Labels: type: feature

#792 fix: correctly zip symlinks
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  src/archive.ts
  src/runtimes/node/utils/zip.ts
  tests/fixtures/node-module-symlinks/node_modules/.pnpm/is-even@1.0.0/node_modules/is-even/index.js
  tests/fixtures/node-module-symlinks/node_modules/.pnpm/is-even@1.0.0/node_modules/is-even/package.json
  tests/fixtures/node-module-symlinks/node_modules/.pnpm/is-even@1.0.0/node_modules/is-odd
  tests/fixtures/node-module-symlinks/node_modules/.pnpm/is-odd@1.0.0/node_modules/is-odd/index.js
  tests/fixtures/node-module-symlinks/node_modules/.pnpm/is-odd@1.0.0/node_modules/is-odd/package.json
  tests/fixtures/node-module-symlinks/node_modules/is-even
  tests/helpers/main.js
  tests/main.js
Labels: type: bug, automerge

#904 chore: fix flaky tests on windows
  tests/helpers/main.js
  tests/main.js
Labels: type: chore

#899 feat: add in-source-config detection to listFunctions
  src/main.ts
  src/runtimes/go/index.ts
  src/runtimes/index.ts
  src/runtimes/node/finder.ts
  src/runtimes/node/index.ts
  src/runtimes/runtime.ts
  src/runtimes/rust/index.ts
  tests/main.js
Labels: type: feature, automerge
