Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-01, with the labels that each got.

#287 chore(deps): disable precinct major updates
  renovate.json5
Labels: type: chore

#295 fix: don't fail if critters is missing on Next.js>=10.0.4
  src/node_dependencies/nested.js
  tests/fixtures/node-module-next10-critters/function/function.js
  tests/fixtures/node-module-next10-critters/function/renderNextPage.js
  tests/fixtures/node-module-next10-critters/node_modules/next/dist/next-server/server/render.js
  tests/fixtures/node-module-next10-critters/node_modules/next/index.js
  tests/fixtures/node-module-next10-critters/node_modules/next/package.json
  tests/fixtures/node-module-next10-critters/package.json
  tests/fixtures/node-module-next9-critters/function.js
  tests/fixtures/node-module-next9-critters/package.json
  tests/main.js
Labels: type: bug

#297 fix: fossa error due to configuration errors
  .github/workflows/fossa.yml
Labels: type: bug

#299 fix: match Next.js exact versions when ignoring critters
  src/node_dependencies/nested.js
  tests/fixtures/node-module-next10-critters-exact/function/function.js
  tests/fixtures/node-module-next10-critters-exact/function/renderNextPage.js
  tests/fixtures/node-module-next10-critters-exact/node_modules/next/dist/next-server/server/render.js
  tests/fixtures/node-module-next10-critters-exact/node_modules/next/index.js
  tests/fixtures/node-module-next10-critters-exact/node_modules/next/package.json
  tests/fixtures/node-module-next10-critters-exact/package.json
  tests/main.js
Labels: type: bug

#301 chore: add prepublish script
  package.json
Labels: type: chore

#300 chore: add PR labeler
  .github/workflows/labeler.yml
Labels: type: chore

#302 feat: allow to configure Node.js resolve paths
  src/main.js
  src/node_dependencies/index.js
  src/node_dependencies/resolve.js
  src/node_dependencies/side_files.js
  src/node_dependencies/tree_files.js
  src/zip_node.js
  tests/fixtures/node-module-next-image/.netlify/plugins/node_modules/next/image.js
  tests/fixtures/node-module-next-image/function/function.js
  tests/fixtures/node-module-next-image/function/renderNextPage.js
  tests/fixtures/node-module-next-image/package.json
  tests/main.js
Labels: type: feature

#307 fix: add missing use case for matching critter dependecy
  src/node_dependencies/nested.js
  tests/fixtures/node-module-next10-critters-10.0.5-range/function/function.js
  tests/fixtures/node-module-next10-critters-10.0.5-range/function/renderNextPage.js
  tests/fixtures/node-module-next10-critters-10.0.5-range/node_modules/next/dist/next-server/server/render.js
  tests/fixtures/node-module-next10-critters-10.0.5-range/node_modules/next/index.js
  tests/fixtures/node-module-next10-critters-10.0.5-range/node_modules/next/package.json
  tests/fixtures/node-module-next10-critters-10.0.5-range/package.json
  tests/main.js
Labels: type: bug

#310 chore: support Node 15
  .github/workflows/workflow.yml
Labels: type: chore

#312 fix: ignore critters if next version = latest
  src/node_dependencies/nested.js
  tests/fixtures/node-module-next10-critters-latest/function/function.js
  tests/fixtures/node-module-next10-critters-latest/function/renderNextPage.js
  tests/fixtures/node-module-next10-critters-latest/node_modules/next/dist/next-server/server/render.js
  tests/fixtures/node-module-next10-critters-latest/node_modules/next/index.js
  tests/fixtures/node-module-next10-critters-latest/node_modules/next/package.json
  tests/fixtures/node-module-next10-critters-latest/package.json
  tests/main.js
Labels: type: bug

#314 fix: add `prisma` CLI to EXCLUDED_PEER_DEPENDENCIES
  src/node_dependencies/nested.js
Labels: type: feature
