Repository netlify/zip-it-and-ship-it, pull requests merged in 2021-06, with the labels that each got.

#515 fix: add default bundler to listFunctions and listFunctionsFiles calls
  src/main.js
  src/runtimes/node/index.js
  src/runtimes/node/src_files.js
  tests/fixtures/list/five/index.ts
  tests/fixtures/list/five/util.ts
  tests/main.js
Labels: type: bug

#516 feat: replace esbuild with @netlify/esbuild
  package-lock.json
  package.json
  src/runtimes/node/bundler.js
  src/runtimes/node/dynamic_imports.js
  src/runtimes/node/native_modules/plugin.js
Labels: type: feature

#526 feat: upgrade esbuild to @netlify/esbuild@0.13.5
  package-lock.json
  package.json
  tests/fixtures/node-typescript-tsconfig-target/functions/function.ts
  tests/fixtures/node-typescript-tsconfig-target/node_modules/module-name/index.js
  tests/fixtures/node-typescript-tsconfig-target/node_modules/module-name/package.json
  tests/fixtures/node-typescript-tsconfig-target/tsconfig.json
  tests/main.js
Labels: type: feature

#534 fix: add limit to log lines produced by esbuild
  src/runtimes/node/bundler.js
  tests/fixtures/esbuild-log-limit/function.js
  tests/main.js
Labels: type: bug

#538 fix: add aws-sdk to ignored_node_modules
  src/node_dependencies/special_cases.js
  tests/fixtures/node-module-excluded/function.js
  tests/fixtures/node-module-excluded/node_modules/aws-sdk/index.js
  tests/fixtures/node-module-excluded/node_modules/aws-sdk/package.json
  tests/main.js
Labels: type: bug

#521 feat: handle dynamic imports
  package-lock.json
  package.json
  src/runtimes/node/bundler.js
  src/runtimes/node/dynamic_imports.js
  src/runtimes/node/dynamic_imports/parser.js
  src/runtimes/node/dynamic_imports/plugin.js
  src/runtimes/node/zip_esbuild.js
  src/utils/fs.js
  tests/fixtures/node-module-dynamic-import-2/function.js
  tests/fixtures/node-module-dynamic-import-2/lang/en.json
  tests/fixtures/node-module-dynamic-import-2/lang/pt.json
  tests/fixtures/node-module-dynamic-import-2/package.json
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test/index.js
  tests/helpers/main.js
  tests/main.js
Labels: type: feature

#544 fix: add guards in JS parsing
  src/runtimes/node/dynamic_imports/parser.js
Labels: type: bug

#546 feat: add more expressions to dynamic import parser
  src/runtimes/node/dynamic_imports/parser.js
  tests/fixtures/node-module-dynamic-import-template-literal/function.js
  tests/fixtures/node-module-dynamic-import-template-literal/node_modules/@org/test/files/one.js
  tests/fixtures/node-module-dynamic-import-template-literal/node_modules/@org/test/index.js
  tests/fixtures/node-module-dynamic-import-template-literal/node_modules/@org/test/package.json
  tests/fixtures/node-module-dynamic-import-template-literal/package.json
  tests/fixtures/node-module-dynamic-import-unresolvable/function.js
  tests/fixtures/node-module-dynamic-import-unresolvable/node_modules/@org/test/files/one.js
  tests/fixtures/node-module-dynamic-import-unresolvable/node_modules/@org/test/index.js
  tests/fixtures/node-module-dynamic-import-unresolvable/node_modules/@org/test/package.json
  tests/fixtures/node-module-dynamic-import-unresolvable/package.json
  tests/fixtures/node-module-dynamic-import/node_modules/@org/test/index.js
  tests/fixtures/node-module-dynamic-import/node_modules/test-two/index.js
  tests/main.js
Labels: type: feature

#552 chore: add test
  tests/main.js
Labels: type: chore

#554 chore: add Next.js E2E test workflow
  .github/workflows/e2e-nextjs.yml
Labels: type: chore

#559 feat: add processDynamicNodeImports config property
  src/runtimes/node/bundler.js
  src/runtimes/node/dynamic_imports/plugin.js
  tests/main.js
Labels: type: feature

#563 chore(ci): add prerelease action
  .github/workflows/pre-release.yml
  CONTRIBUTING.md
Labels: type: chore

#562 feat: remove `experimentalHandlerV2` config property
  src/runtimes/node/zip_esbuild.js
  src/runtimes/node/zip_zisi.js
  src/zip_node.js
  tests/main.js
Labels: type: feature

#565 chore: update Next.js E2E flow with monorepo support
  .github/workflows/e2e-nextjs.yml
Labels: type: chore

#566 chore: remove CLI feature flag from Next.js E2E workflow
  .github/workflows/e2e-nextjs.yml
Labels: type: chore
