Repository netlify/zip-it-and-ship-it, pull requests merged in 2022-08, with the labels that each got.

#1166 chore: create codeql-analysis.yml
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: type: chore, automerge

#1179 feat: convert Runtime, NodeBundler and ModuleFormat to enums
  .eslintrc.cjs
  src/config.ts
  src/main.ts
  src/runtimes/detect_runtime.ts
  src/runtimes/go/builder.ts
  src/runtimes/go/index.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/bundler_target.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/bundlers/nft/es_modules.ts
  src/runtimes/node/bundlers/nft/transpile.ts
  src/runtimes/node/bundlers/types.ts
  src/runtimes/node/bundlers/zisi/index.ts
  src/runtimes/node/bundlers/zisi/list_imports.ts
  src/runtimes/node/in_source_config/index.ts
  src/runtimes/node/index.ts
  src/runtimes/node/utils/entry_file.ts
  src/runtimes/node/utils/module_format.ts
  src/runtimes/runtime.ts
  src/runtimes/rust/builder.ts
  src/runtimes/rust/index.ts
  src/utils/error.ts
  src/utils/format_result.ts
Labels: type: feature, automerge, area: typescript

#1173 feat: new bundler that allows to skip bundling
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/bundlers/none/index.ts
  src/runtimes/node/bundlers/types.ts
  src/runtimes/node/index.ts
  src/runtimes/node/utils/package_json.ts
  tests/helpers/main.js
  tests/helpers/test_many.js
  tests/main.js
  tests/snapshots/main.js.md
  tests/snapshots/main.js.snap
Labels: type: feature, automerge

#1030 feat: add support to per-function configuration files
  package-lock.json
  package.json
  src/config.ts
  src/feature_flags.ts
  src/runtimes/index.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/bundlers/none/index.ts
  src/runtimes/node/bundlers/types.ts
  src/runtimes/node/index.ts
  src/runtimes/node/utils/package_json.ts
  src/zip.ts
  tests/fixtures/config-files-invalid-version/blog/one.md
  tests/fixtures/config-files-invalid-version/my-function-1/my-function-1.js
  tests/fixtures/config-files-invalid-version/my-function-1/my-function-1.json
  tests/fixtures/config-files-invalid-version/my-function-2.js
  tests/fixtures/config-files-invalid-version/my-function-2.json
  tests/fixtures/config-files-malformed-json/blog/one.md
  tests/fixtures/config-files-malformed-json/my-function-1/my-function-1.js
  tests/fixtures/config-files-malformed-json/my-function-1/my-function-1.malformed-json
  tests/fixtures/config-files-malformed-json/my-function-2.js
  tests/fixtures/config-files-malformed-json/my-function-2.malformed-json
  tests/fixtures/config-files-select-directories/.netlify/functions-internal-not/not-internal.js
  tests/fixtures/config-files-select-directories/.netlify/functions-internal-not/not-internal.json
  tests/fixtures/config-files-select-directories/.netlify/functions-internal/internal-function/internal-function.js
  tests/fixtures/config-files-select-directories/.netlify/functions-internal/internal-function/internal-function.json
  tests/fixtures/config-files-select-directories/.netlify/functions-internal/root-function.js
  tests/fixtures/config-files-select-directories/.netlify/functions-internal/root-function.json
  tests/fixtures/config-files-select-directories/blog/one.md
  tests/fixtures/config-files-select-directories/netlify/functions/user-function/user-function.js
  tests/fixtures/config-files-select-directories/netlify/functions/user-function/user-function.json
  tests/helpers/main.js
  tests/helpers/test_many.js
  tests/main.js
  tests/snapshots/main.js.md
  tests/snapshots/main.js.snap
Labels: type: feature

#1182 feat: support tsx, mts, cts and cjs for functions
  README.md
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/finder.ts
  tests/fixtures/node-cjs-extension/func1.cjs
  tests/fixtures/node-cjs-extension/func2/func2.cjs
  tests/fixtures/node-cjs-extension/func3/index.cjs
  tests/fixtures/node-cjs-importing-mjs-extension/function.js
  tests/fixtures/node-cjs-importing-mjs-extension/lib/file.mjs
  tests/fixtures/node-cts-extension/func1.cts
  tests/fixtures/node-cts-extension/func2/func2.cts
  tests/fixtures/node-cts-extension/func3/index.cts
  tests/fixtures/node-mjs-extension/func1.mjs
  tests/fixtures/node-mjs-extension/func2/func2.mjs
  tests/fixtures/node-mjs-extension/func3/index.mjs
  tests/fixtures/node-mts-extension/func1.mts
  tests/fixtures/node-mts-extension/func2/func2.mts
  tests/fixtures/node-mts-extension/func3/index.mts
  tests/fixtures/node-tsx-extension/func1.tsx
  tests/fixtures/node-tsx-extension/func2/func2.tsx
  tests/fixtures/node-tsx-extension/func3/index.tsx
  tests/main.js
Labels: type: feature, automerge
