Repository netlify/zip-it-and-ship-it, pull requests merged in 2022-11, with the labels that each got.

#1214 feat: zisi system logging
  src/utils/logger.ts
  src/utils/timer.ts
  src/zip.ts
  tests/unit/utils/logger.test.ts
Labels: type: feature

#1274 fix: (backport) make esbuild work with ESM and require calls (#1257)
  .eslintrc.cjs
  src/feature_flags.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  tests/fixtures/node-require-in-esm/functions/func1.mjs
  tests/fixtures/node-require-in-esm/include.cjs
  tests/main.js
Labels: type: bug, backport

#1275 chore: Update CHANGELOG for 7.1.3 on main branch
  CHANGELOG.md
Labels: automerge
