Repository netlify/zip-it-and-ship-it, pull requests merged in 2022-05, with the labels that each got.

#1083 feat: update precinct
  package-lock.json
  package.json
  src/runtimes/node/bundlers/zisi/src_files.ts
Labels: type: chore, type: feature

#1084 chore: add "cypress passed" comment to integration test
  .github/workflows/integration-tests.yml
Labels: type: chore, automerge

#1086 fix(nft): correctly annotate transpilation errors in nft bundler
  src/runtimes/node/bundlers/nft/es_modules.ts
  src/runtimes/node/bundlers/nft/index.ts
  src/runtimes/node/bundlers/nft/transpile.ts
  tests/fixtures/node-esm-top-level-await-error/function.js
  tests/main.js
Labels: type: bug
