Repository netlify/zip-it-and-ship-it, pull requests merged in 2022-01, with the labels that each got.

#934 fix: fix a few typos
  README.md
  src/runtimes/node/bundlers/zisi/resolve.ts
  src/runtimes/node/parser/index.ts
Labels: type: chore, automerge

#931 chore: replace nyc with c8
  .gitignore
  package-lock.json
  package.json
Labels: type: chore, automerge

#929 fix: use es2019 in tsconfig
  tsconfig.json
Labels: type: bug, automerge

#930 fix: remove make-dir package and use `fs/promises`
  package-lock.json
  package.json
  src/manifest.ts
  src/runtimes/go/builder.ts
  src/runtimes/node/finder.ts
  src/runtimes/node/parser/index.ts
  src/runtimes/node/utils/detect_es_module.ts
  src/runtimes/node/utils/zip.ts
  src/runtimes/rust/builder.ts
  src/utils/archive_size.ts
  src/utils/fs.ts
  src/zip.ts
  tests/main.js
Labels: type: bug, automerge

#947 chore(deps): remove typescript from devDeps since it's a dependency
  package-lock.json
  package.json
Labels: automerge

#949 chore: fix Husky
  package-lock.json
  package.json
Labels: type: chore, automerge

#950 fix: husky binary not found
  package-lock.json
  package.json
Labels: type: bug, automerge

#957 feat: zip Go functions from source when `zipGo` is enabled
  src/runtimes/go/index.ts
  tests/main.js
Labels: type: feature, automerge

#966 fix: pin `@babel/parser` to `7.16.8`
  package-lock.json
  package.json
Labels: type: bug, automerge
