Repository netlify/zip-it-and-ship-it, pull requests merged in 2022-06, with the labels that each got.

#1039 refactor: consolidate getPackageJson and remove pkg-dir dependency
  package-lock.json
  package.json
  src/runtimes/node/utils/package_json.ts
Labels: type: chore, automerge

#1103 lock file maintenance
  package-lock.json
  tests/helpers/main.js
  tests/main.js
Labels: type: chore, automerge

#1105 fix: detect a wider range of scheduled functions
  src/runtimes/node/in_source_config/index.ts
  src/runtimes/node/in_source_config/properties/schedule.ts
  src/runtimes/node/parser/bindings.ts
  src/runtimes/node/parser/exports.ts
  tests/fixtures/in-source-config/functions/cron_esm_no_direct_export.js
  tests/fixtures/in-source-config/functions/cron_esm_no_direct_export_renamed.js
  tests/fixtures/in-source-config/functions/cron_esm_no_direct_export_renamed_reassigned.js
  tests/fixtures/in-source-config/functions/cron_esm_schedule_reassigned.js
  tests/main.js
Labels: type: bug, automerge, area: functions

#1107 chore: enforce newline before return and after variable declarations
  .eslintrc.cjs
  src/archive.ts
  src/bin.ts
  src/main.ts
  src/runtimes/go/builder.ts
  src/runtimes/index.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/zisi/list_imports.ts
  src/runtimes/node/bundlers/zisi/published.ts
  src/runtimes/node/bundlers/zisi/resolve.ts
  src/runtimes/node/bundlers/zisi/side_files.ts
  src/runtimes/node/bundlers/zisi/src_files.ts
  src/runtimes/node/bundlers/zisi/traverse.ts
  src/runtimes/node/in_source_config/properties/schedule.ts
  src/runtimes/node/index.ts
  src/runtimes/node/parser/bindings.ts
  src/runtimes/node/parser/exports.ts
  src/runtimes/node/utils/module.ts
  src/runtimes/node/utils/normalize_path.ts
  src/runtimes/node/utils/package_json.ts
  src/utils/matching.ts
  src/zip_binary.ts
Labels: type: chore, automerge

#1109 chore: Enable lockfile maintenance
  renovate.json5
Labels: type: chore, automerge

#1113 refactor: remove feature flag buildGoSource and zisi_detect_esm
  src/feature_flags.ts
  src/runtimes/go/index.ts
  src/runtimes/node/bundlers/index.ts
  tests/main.js
Labels: type: chore

#1119 fix: handle invalid `files` entry in package.json
  src/runtimes/node/utils/detect_native_module.ts
Labels: type: bug

#1121 fix: always build for amd64 when building go functions
  src/runtimes/go/builder.ts
Labels: type: bug
