Repository netlify/zip-it-and-ship-it, pull requests merged in 2022-02, with the labels that each got.

#1001 chore: re-pin `@babel/parser` version
  package-lock.json
  package.json
  renovate.json5
Labels: type: chore

#1002 feat: adds `getNodeVersion` util
  .eslintrc.js
  package.json
  src/config.ts
  src/runtimes/node/index.ts
  src/runtimes/node/utils/node_version.ts
  tests/main.js
  tests/unit/runtimes/node/utils/node_version.js
  tests/unit/runtimes/node/utils/package_json.js
Labels: type: feature, automerge

#1004 feat: generate pure ESM functions for NFT
  src/config.ts
  src/feature_flags.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/index.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/bundlers/nft/es_modules.ts
  src/runtimes/node/bundlers/nft/index.ts
  src/runtimes/node/bundlers/zisi/index.ts
  src/runtimes/node/bundlers/zisi/list_imports.ts
  src/runtimes/node/index.ts
  src/runtimes/node/utils/entry_file.ts
  src/runtimes/node/utils/module_format.ts
  src/runtimes/node/utils/node_version.ts
  src/runtimes/node/utils/normalize_path.ts
  src/runtimes/node/utils/zip.ts
  src/runtimes/runtime.ts
  tests/fixtures/node-esm/func1.js
  tests/fixtures/node-esm/func2/func2.js
  tests/fixtures/node-esm/package.json
  tests/main.js
Labels: type: feature, automerge

#991 chore: upgrade benchmark's code dependencies
  benchmarks/fixtures/package-lock.json
Labels: type: chore, automerge

#971 fix: rename `.eslintrc.js` to `.eslintrc.cjs`
  .eslintrc.cjs
  package.json
Labels: type: chore, automerge

#970 fix: rename `commitlint.config.js` to `commitlint.config.cjs`
  commitlint.config.cjs
Labels: type: chore, automerge

#975 chore: use common `FIXTURES_DIR` in benchmarks
  benchmarks/esbuild.js
  benchmarks/helpers/main.js
  benchmarks/nft.js
  benchmarks/zisi.js
Labels: type: chore

#973 chore: add support for `.cjs`, `.cts`, `.mjs` and `.mts`
  package.json
Labels: type: chore

#1007 fix: guard against self-referencing element in `shouldTranspile`
  src/runtimes/node/bundlers/nft/es_modules.ts
Labels: type: bug, automerge

#977 chore: use ES modules in benchmarks
  benchmarks/esbuild.js
  benchmarks/helpers/main.js
  benchmarks/nft.js
  benchmarks/package.json
  benchmarks/zisi.js
Labels: type: chore

#981 fix: use `FIXTURES_DIR` in tests
  tests/main.js
Labels: type: chore

#979 fix: use `BINARY_PATH` constant in tests
  tests/bin.js
  tests/helpers/main.js
  tests/main.js
Labels: type: chore

#983 fix: fix `shellUtils` stubbing with ES modules
  src/runtimes/go/builder.ts
  src/runtimes/rust/builder.ts
  src/utils/shell.ts
  tests/main.js
Labels: type: chore, automerge

#984 fix: use new interface of Yargs
  src/bin.ts
Labels: type: chore, automerge

#985 fix: semver imports
  src/runtimes/node/bundlers/zisi/nested.ts
  src/runtimes/node/bundlers/zisi/resolve.ts
Labels: type: chore, automerge

#1008 fix: use safe version of `getPackageJson` when transpiling ESM
  src/runtimes/node/bundlers/esbuild/special_cases.ts
  src/runtimes/node/bundlers/nft/es_modules.ts
  src/runtimes/node/utils/package_json.ts
Labels: type: bug, automerge

#972 fix: upgrade TypeScript
  package-lock.json
  package.json
Labels: type: chore, automerge

#980 fix: use dynamic `import()` in tests
  .eslintrc.cjs
  tests/helpers/main.js
  tests/main.js
Labels: type: chore

#978 fix: use ES modules in README.md
  .eslintrc.cjs
  README.md
Labels: type: chore, automerge

#982 fix: fix JSON imports for ES modules
  .eslintrc.cjs
  src/runtimes/node/bundlers/zisi/traverse.ts
  src/runtimes/node/utils/package_json.ts
  tests/bin.js
  tests/main.js
Labels: type: chore, automerge

#974 fix: use `.js` and `index.js` in imports
  .eslintrc.cjs
  src/bin.ts
  src/config.ts
  src/function.ts
  src/main.ts
  src/manifest.ts
  src/runtimes/detect_runtime.ts
  src/runtimes/go/builder.ts
  src/runtimes/go/index.ts
  src/runtimes/index.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/index.ts
  src/runtimes/node/bundlers/esbuild/plugin_dynamic_imports.ts
  src/runtimes/node/bundlers/esbuild/plugin_native_modules.ts
  src/runtimes/node/bundlers/esbuild/special_cases.ts
  src/runtimes/node/bundlers/esbuild/src_files.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/bundlers/nft/es_modules.ts
  src/runtimes/node/bundlers/nft/index.ts
  src/runtimes/node/bundlers/nft/transpile.ts
  src/runtimes/node/bundlers/zisi/index.ts
  src/runtimes/node/bundlers/zisi/list_imports.ts
  src/runtimes/node/bundlers/zisi/nested.ts
  src/runtimes/node/bundlers/zisi/side_files.ts
  src/runtimes/node/bundlers/zisi/src_files.ts
  src/runtimes/node/bundlers/zisi/traverse.ts
  src/runtimes/node/bundlers/zisi/tree_shake.ts
  src/runtimes/node/finder.ts
  src/runtimes/node/in_source_config/index.ts
  src/runtimes/node/in_source_config/properties/schedule.ts
  src/runtimes/node/index.ts
  src/runtimes/node/parser/exports.ts
  src/runtimes/node/parser/imports.ts
  src/runtimes/node/parser/index.ts
  src/runtimes/node/utils/detect_native_module.ts
  src/runtimes/node/utils/entry_file.ts
  src/runtimes/node/utils/zip.ts
  src/runtimes/runtime.ts
  src/runtimes/rust/builder.ts
  src/runtimes/rust/index.ts
  src/utils/archive_size.ts
  src/utils/format_result.ts
  src/utils/fs.ts
  src/zip.ts
  src/zip_binary.ts
  tests/bin.js
  tests/feature_flags.js
  tests/fixtures/list/five/index.ts
  tests/fixtures/node-typescript-with-imports/function.ts
  tests/helpers/main.js
  tests/main.js
  tests/unit/runtimes/node/utils/node_version.js
  tests/unit/runtimes/node/utils/package_json.js
Labels: type: chore, automerge

#1019 chore: move typescript to dev dependencies
  package.json
Labels: type: chore, automerge

#1020 chore: move `typescript` to `devDependencies` in lock file
  package-lock.json
Labels: type: chore, automerge

#1018 feat: add pure ESM support to esbuild and default bundlers
  src/feature_flags.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/bundler_target.ts
  src/runtimes/node/bundlers/esbuild/index.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/utils/package_json.ts
  tests/main.js
Labels: type: feature, automerge

#1037 fix: pin down esbuild version
  package-lock.json
  package.json
Labels: type: bug, automerge
