Repository netlify/zip-it-and-ship-it, pull requests merged in 2022-07, with the labels that each got.

#1122 chore: report unused eslint disable statements
  package.json
Labels: type: chore, automerge

#1133 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore

#1124 feat: detect invalid binaries and show warning
  package-lock.json
  package.json
  src/bin.ts
  src/runtimes/detect_runtime.ts
  tests/fixtures/wrong-prebuilt-architecture/go-arm64
  tests/main.js
Labels: type: feature, automerge

#1138 feat: update default nodejs version to 16
  README.md
  src/runtimes/node/bundlers/esbuild/bundler_target.ts
  src/runtimes/node/utils/node_version.ts
  tests/unit/runtimes/node/utils/node_version.js
Labels: type: feature, automerge

#1134 fix: add more error info on missing functions folders
  src/utils/fs.ts
  tests/fixtures/missing-functions-folder/.keep
  tests/main.js
Labels: type: bug, automerge

#1146 fix: annotate ISC errors and split into to separate errors
  src/config.ts
  src/main.ts
  src/runtimes/go/builder.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/index.ts
  src/runtimes/node/bundlers/esbuild/plugin_native_modules.ts
  src/runtimes/node/bundlers/esbuild/src_files.ts
  src/runtimes/node/bundlers/index.ts
  src/runtimes/node/bundlers/nft/index.ts
  src/runtimes/node/bundlers/nft/transpile.ts
  src/runtimes/node/bundlers/types.ts
  src/runtimes/node/bundlers/zisi/index.ts
  src/runtimes/node/bundlers/zisi/list_imports.ts
  src/runtimes/node/bundlers/zisi/src_files.ts
  src/runtimes/node/in_source_config/index.ts
  src/runtimes/node/index.ts
  src/runtimes/runtime.ts
  src/runtimes/rust/builder.ts
  src/utils/error.ts
  tests/fixtures/in-source-config/functions/cron_esm_schedule_multi_import.js
  tests/fixtures/in-source-config/functions_missing_schedule_usage/cron_cjs_schedule_not_called.js
  tests/fixtures/in-source-config/functions_missing_schedule_usage/cron_esm_schedule_not_called.js
  tests/main.js
Labels: type: bug, automerge

#1161 fix: add node 16 to valid types and be more strict about version in esbuild types
  src/runtimes/node/bundlers/esbuild/bundler_target.ts
  src/runtimes/node/utils/node_version.ts
Labels: type: bug, automerge
