Repository netlify/zip-it-and-ship-it, pull requests merged in 2023-01, with the labels that each got.

#1190 feat: output cjs extension for bundles and entry-files
  .eslintrc.cjs
  src/feature_flags.ts
  src/runtimes/node/bundlers/esbuild/bundler.ts
  src/runtimes/node/bundlers/esbuild/index.ts
  src/runtimes/node/utils/entry_file.ts
  src/runtimes/node/utils/module_format.ts
  src/runtimes/node/utils/zip.ts
  tests/fixtures/node-js-extension/func1.js
  tests/fixtures/node-js-extension/func2/func2.js
  tests/fixtures/node-js-extension/func3/index.js
  tests/main.test.ts
Labels: type: chore, type: feature, automerge

#1308 Test: add a unit test for addArchiveSize
  package.json
  tests/fixtures/archive-size/normal.js
  tests/fixtures/archive-size/normal.zip
  tests/unit/utils/archive_size.test.ts
Labels: type: chore

#1221 feat: Make additional function attributes available via functions manifest
  README.md
  src/config.ts
  src/manifest.ts
  src/runtimes/go/index.ts
  src/runtimes/node/index.ts
  src/runtimes/runtime.ts
  src/runtimes/rust/index.ts
  src/zip.ts
  tests/fixtures/go-internal/.netlify/internal-functions/go-func-1/main.go
  tests/fixtures/go-internal/.netlify/internal-functions/go-func-2/go-func-2.go
  tests/fixtures/go-internal/.netlify/internal-functions/go-func-2/go.mod
  tests/fixtures/go-internal/.netlify/internal-functions/go-func-2/go.sum
  tests/fixtures/node-display-name/function-1.js
  tests/fixtures/node-internal/.netlify/internal-functions/function-1.js
  tests/fixtures/node-internal/.netlify/internal-functions/function-2.js
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-1/.gitignore
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-1/Cargo.lock
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-1/Cargo.toml
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-1/src/main.rs
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-2/.gitignore
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-2/Cargo.lock
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-2/Cargo.toml
  tests/fixtures/rust-internal/.netlify/internal-functions/rust-func-2/src/main.rs
  tests/main.test.ts
  tests/zip_function.test.ts
Labels: type: feature

#1324 docs: add nft to nodeBundler in the docs
  README.md
Labels: type: chore

#1329 feat: return displayName with json config from listFunction, listFunctions and listFunctionsFiles
  README.md
  src/main.ts
  src/runtimes/index.ts
  tests/fixtures/json-config/.netlify/functions-internal/simple.js
  tests/fixtures/json-config/.netlify/functions-internal/simple.json
  tests/list_function.test.ts
  tests/list_functions.test.ts
  tests/list_functions_files.test.ts
Labels: type: feature

#1328 feat: disallow unique entry file name
  src/feature_flags.ts
  src/runtimes/index.ts
  src/runtimes/node/utils/entry_file.ts
  src/runtimes/node/utils/zip.ts
  tests/fixtures/entry-file-file-name/___netlify-entry-point/other.js
  tests/fixtures/entry-file-file-name/func1.js
  tests/fixtures/entry-file-func-name/___netlify-entry-point.js
  tests/main.test.ts
Labels: automerge
